version: 0.2
phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo $URL
      - sudo yum -y install iputils
      - ping -c 5 www.bbc.co.uk 
  build:
    steps:
      - uses: liquibase-github-actions/update@v4.21.1
        with: 
          changelogFile: changelog-root.sql
          url: ${{ env.URL }}
          username: postgres
          password: ${{ $env.PASSWORD }}
          headless: true
          logLevel: DEBUG
