version: 0.2
phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo $URL
  build:
    steps:
      - name: set password var
        id: vars
        run: echo "DB_PASSWORD=$(echo ${{ env.PASSWORD }} | jq '.password')" >> $GITHUB_OUTPUT
      - name: liquibase schema update
        uses: liquibase-github-actions/update@v4.21.1
        with: 
          changelogFile: "changelog-root.sql"
          url: "${{ env.URL }}"
          username: "postgres"
          password: ${{ steps.vars.outputs.DB_PASSWORD }}
          headless: true
          logLevel: DEBUG
